project:
  type: website
  output-dir: docs

website:
  title: "DS_sol"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: hw1.qmd
        text: Homework1
      - href: hw2.qmd
        text: Homework2
      - href: crime.qmd
        text: project1_Crime
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



