---
title: "LS 빅데이터 스쿨 Homework 2"
author: "이예솔"
date: "2024-07-16"
categories: [bigdata]
---

## Q1. 자동차 배기량에 따라 고속도로 연비가 다른지 알아보려고 합니다.`displ`(배기량)이 4 이하인 자동차와 5 이상인 자동차 중 어떤 자동차의 `hwy`(고속도로 연비) 평균이 더 높은지 알아보세요.
### A1-1. mpg데이터 불러오기
```{python}
import pandas as pd
df_mpg= pd.read_csv('data/mpg.csv')
mpg = df_mpg.copy()
mpg.head()
```
### A1-2. 배기량이 4이하인 자동차의 고속도로 연비 평균
```{python}
mpg.query('displ <= 4')['hwy'].mean()
```
### A1-3. 배기량이 5이상인 자동차의 고속도로 연비 평균
```{python}
mpg.query('displ >= 5')['hwy'].mean()
```
### A1-4. 배기량에 따른 고속도로 연비 평균 비교
배기량이 4이하인 자동차의 고속도로 연비 평균이 더 높다.

## Q2. 자동차 제조 회사에 따라 도시 연비가 어떻게 다른지 알아보려고 합니다. `audi`와 `toyota` 중 어느 `manufacturer`(자동차 제조 회사)의 `cty`(도시 연비) 평균이 더 높은지 알아보세요.
### A2-1. `audi`의 `cty` 평균
```{python}
mpg.query('manufacturer == "audi"')['cty'].mean()
```
### A2-2. `toyota`의 `cty`평균
```{python}
mpg.query(' manufacturer == "toyota" ')['cty'].mean()
```
### A2-3. 자동차 제조회사별 도시연비 평균 비교
도요타의 도시연비 평균이 더 높다

### A2-4. groupby 이용해서 풀어보기
```{python}
mpg.groupby('manufacturer',as_index=False)\
   .agg(mean_cty=('cty','mean'))\
   .query('manufacturer in ["audi","toyota"] ')
```
## Q3. `chevrolet`, `ford`, `honda` 자동차의 고속도로 연비 평균을 알아보려고 합니다. 세 회사의 데이터를 추출한 다음 hwy 전체 평균을 구해보세요.
### A3. 세 회사의 고속도로 연비 전체 평균
```{python}
mpg.query('manufacturer in ["chevrolet","ford","honda"] ')['hwy'].mean()
```
## Q4. `audi`에서 생산한 자동차 중에 어떤 자동차 모델의 `hwy`(고속도로 연비)가 높은지 알아보려고 합니다. `audi`에서 생산한 자동차 중 `hwy`가 1~5위에 해당하는 자동차의 데이터를 출력하세요.

### A4. `audi` 자동차 중 `hwy`가 1~5위에 해당하는 자동차의 데이터 출력
```{python}
mpg.query('manufacturer == "audi"').sort_values('hwy', ascending=False).head()
```
## Q5. `mpg` 데이터 복사본을 만들고, `cty`와 `hwy`를 더한 '합산 연비 변수'를 추가하세요.
### A5-1. 데이터 복사본 생성
```{python}
mpg_raw = pd.read_csv('data/mpg.csv')
mpg = mpg_raw.copy()
mpg.head()
```
### A5-2. 합산 연비 변수 생성
```{python}
mpg=mpg.assign(total=(mpg['cty']+mpg['hwy']))
mpg.head()
```
## Q6. 앞에서 만든 '합산 연비 변수'를 2로 나눠 '평균 연비 변수'를 추가하세요
### A6. 평균 연비 변수 생성
```{python}
mpg = mpg.assign(mean = mpg['total'] / 2)
mpg.head()
```
## Q7. '평균 연비 변수'가 가장 높은 자동차 3종의 데이터를 출력하세요.
### A7. 평균 연비 변수가 가장 높은 자동차 3종 데이터 출력
```{python}
mpg.sort_values('mean',ascending=False).head(3)
```

## Q8. 5~7번 문제를 해결할 수 있는 하나로 연결된 `pandas` 구문을 만들어 실행해 보세요. 데이터는 복사본 대신 mpg 원본을 이용하세요.
```{python}
mpg_raw.assign(
    total=lambda x: x['cty']+x['hwy'],
    mean =lambda x: x['total']/2
).sort_values('mean',ascending=False).head(3)
```

