---
title: "LS 빅데이터 스쿨 Homework 7"
author: "이예솔"
date: "2024-09-02"
categories: [bigdata]
---

# 슬통교재 37p ADP 표본점수 ADP ~ N(30,5^2)
## 1. ADP 실기시험의 통계파트 표준점수의밀 도함수를 그려보세요.
```{python}
import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt
x = np.arange(15,45,0.01)
prob = norm.pdf(x, loc=30, scale=5)
plt.plot(x,prob)
```

## 2. ADP수험생을 임의로 1명을 선택하여 통계점수를 조회 했을때 45점보다 높은 점수를 받았을 확률을구하세요.
```{python}
1-norm.cdf(x=45, loc=30, scale=5)
```

## 3. 슬통이는 상위 10%에 해당하는 점수를 얻었다고 한다면, 슬통이의 점수는 얼마인지 계산해보세요.
```{python}
norm.ppf(0.9, loc=30, scale=5)
```

## 4. 슬기로운통계생활의 해당 회차 수강생은 16명이었다고한다. 16명의 통계파트 점수를 평균내었을때, 평균값이 따르는 분포의 확률밀도함수를 1번의 그래프와 겹쳐 그려보세요.
```{python}
# 중심극한정리에 의해 표본평균의 확률변수 X_bar ~ N(30, 5^2/16)

plt.plot(x,prob, color = 'blue')

prob_16 = norm.pdf(x, loc=30, scale=5/np.sqrt(16))
plt.plot(x,prob_16,color='red')
```

## 5. 슬기로운통계생활 ADP반 수강생들의 통계점수를 평균내었다고할때, 이값이 38점보다 높게 나올확률을 구하세요
```{python}
1 - norm.cdf(38,loc=30,scale=5/np.sqrt(16))
```

# COVID19 발병률 1%일때, 코로나 의심 환자들 1,085명을 대상으로 "다잡아"키트를 사용하여 양성반응을 체크한 결과가 다음과 같다.

|키트/실제|양성|음성|
|--------|----|---|
|양성|370|10|
|음성|15|690|

## 1.다잡아 키트가 코로나 바이러스에 걸린 사람을 양성으로 잡아낼 확률을 계산하세요.
```{python}
# P(키트양성|실제양성) = P(키트양성∩실제양성) / P(실제양성)
370/(370+15)
```

## 2. 슬통회사에서 다잡아 키트를 사용해 양성으로 나온 사람이 실제로는 코로나바이러스에 걸려
있을 확률을 97%라며, 키트의 우수성을 주장했다.이 주장이 옳지 않은 이유를 서술하세요.

```{python}
# P(실제양성|키트양성) = P(실제양성∩키트양성) / P(실제양성)
370/(370+10) # 0.974

# 0.97이 아니므로 옳지 않다.
```

## 3. Covid19 발병률을 사용하여, 키트의 결과값이 양성으로 나온 사람이 실제로 코로나 바이러스에 걸려있을 확률을 구하세요.
```{python}
# Covid19 발병률1% => P(실제양성) = 0.01
# P(실제양성|키트양성) = P(실제양성∩키트양성) / P(키트양성) 
# = P(실제양성)P(키트양성|실제양성) / (P(실제양성)P(키트양성|실제양성) + P(실제음성)P(키트양성|실제음성) )
0.01*(370/385) / (0.01*370/385 + 0.99*10/700)
```

# 카이제곱분포와 표본분산 X ~ χ^2(k=자유도)

## 1. 자유도가 4인 카이제곱분포의 확률밀도함수를 그려보세요.
```{python}
from scipy.stats import chi2
x = np.arange(0,20,0.01)
prob = chi2.pdf(x,df=4, loc=0, scale=1)
plt.plot(x,prob)
```

## 2. P(3<=X<=5)의 확률을 구해보세요
```{python}
chi2.cdf(5, df=4, loc=0, scale=1) - chi2.cdf(3, df=4, loc=0, scale=1)
```

## 3. 자유도가 4인 카이제곱분포에서 크기가 1000인 표본을 뽑은 후, 히스토그램을 그려보세요.
```{python}
np.random.seed(20240902)
x_1000 = chi2.rvs(df=4, size=1000)
plt.hist(x_1000, bins=50, density=True)
```

## 4. 자유도가 4인 카이제곱분포를 따르는 확률변수에서 나올 수 잇는 값 중 상위 5%에 해당하는 값은 얼마인지 계산해보세요.
```{python}
chi2.ppf(0.95, df=4, loc=0, scale=1)
```

## 5. 3번에서 뽑힌 표본값들 중 상위 5%에 위치한 표본의 값은 얼마인가요?
```{python}
np.percentile(x_1000, 95)
# 이미 뽑혔으므로 확률변수가 아니라 표본이니까 ppf쓸필요 없음
```

## 6. 확률변수X ~ N(3,2^2)에서 크기가 20인 표본을 뽑은 후 표본분산을 계산한 것을 s1^2라 생각해보고 다음을 수행해보세요.

- 같은방법으로500개의𝑠2들,𝑠2
 1,𝑠2
 2,...,𝑠2
 500발생시킵니다.
- 발생한500개의𝑠2들각각에4.75를곱하고,그것들의히스토그램을그려보세요.(히스토그램
을그릴때probability=TRUE옵션을사용해서그릴것)
- 위에서그린히스토그램에자유도가19인카이제곱분포확률밀도함수를겹쳐그려보세요

```{python}
s_2 = []
for i in range(500):
    x = norm.rvs(loc=3, scale=2, size=20)
    s_2.append(np.var(x, ddof=1))

plt.hist(np.array(s_2)*4.75, bins=50, density=True)
x= np.arange(0,50,0.1)
plt.plot(x, chi2.pdf(x,df=19))
```

